animals = [
    "albatross",
    "alligator",
    "antelope",
    "armadillo",
    "baboon",
    "badger",
    "bat",
    "beagle",
    "bear",
    "beaver",
    "bison",
    "boar",
    "buffalo",
    "bull",
    "camel",
    "cat",
    "chameleon",
    "cheetah",
    "chihuahua",
    "chimpanzee",
    "chinchillas",
    "cobra",
    "cow",
    "crab",
    "crocodile",
    "crow",
    "deer",
    "dodo",
    "dog",
    "dolphin",
    "donkey",
    "duck",
    "eagle",
    "eel",
    "elephant",
    "elk",
    "emu",
    "fish",
    "flamingo",
    "fox",
    "frog",
    "giraffe",
    "goat",
    "goose",
    "gorilla",
    "hamster",
    "hare",
    "hawk",
    "hedgehog",
    "hen",
    "hippopotamus",
    "horse",
    "ibex",
    "iguana",
    "jackal",
    "jaguar",
    "jellyfish",
    "kangaroo",
    "koala",
    "lemur",
    "leopard",
    "lion",
    "lizard",
    "llama",
    "lynx",
    "mammoth",
    "meerkat",
    "mole",
    "monkey",
    "mouse",
    "mule",
    "orangutan",
    "ostrich",
    "otter",
    "owl",
    "panda",
    "panther",
    "peacock",
    "pigeon",
    "porcupine",
    "possum",
    "rabbit",
    "racoon",
    "rat",
    "rhinoceros",
    "sheep",
    "sloth",
    "snake",
    "swan",
    "tiger",
    "tortoise",
    "turtle",
    "vulture",
    "whale",
    "wolf",
    "wombat",
    "zebra",
]

adjectives = [
    "active",
    "adaptable",
    "affectionate",
    "alert",
    "artistic",
    "assertive",
    "boundless",
    "brave",
    "calm",
    "capable",
    "careful",
    "caring",
    "cheerful",
    "clever",
    "comfortable",
    "communicative",
    "compassionate",
    "conscientious",
    "considerate",
    "courageous",
    "creative",
    "decisive",
    "determined",
    "diligent",
    "dynamic",
    "eager",
    "energetic",
    "entertaining",
    "enthusiastic",
    "exuberant",
    "expressive",
    "fabulous",
    "fantastic",
    "fearless",
    "flexible",
    "frank",
    "friendly",
    "funny",
    "generous",
    "gentle",
    "gregarious",
    "happy",
    "helpful",
    "hilarious",
    "honest",
    "imaginative",
    "independent",
    "intellectual",
    "intelligent",
    "intuitive",
    "inventive",
    "joyous",
    "lively",
    "loving",
    "loyal",
    "mature",
    "modest",
    "optimistic",
    "outgoing",
    "passionate",
    "patient",
    "persistent",
    "philosophical",
    "polite",
    "practical",
    "productive",
    "quick",
    "quiet",
    "rational",
    "receptive",
    "reflective",
    "reliable",
    "resourceful",
    "responsible",
    "selective",
    "sensible",
    "sensitive",
    "skillful",
    "straightforward",
    "successful",
    "thoughtful",
    "trustworthy",
    "understanding",
    "versatile",
    "vivacious",
    "warm-hearted",
    "willing",
    "witty",
    "wonderful",
]

maxims = [
    "Success is the child of audacity",
    "Success is one percent inspiration, ninety-nine percent perspiration",
    "You miss 100% of the shots you don’t take",
    "Build your own dreams, or someone else will hire you to build theirs",
    "Fall seven times and stand up eight",
    "There are no shortcuts to any place worth going",
    "Success is not the key to happiness. Happiness is the key to success",
    "The mind is everything. What you think you become",
    "I am not a product of my circumstances. I am a product of my decisions",
    "Remember no one can make you feel inferior without your consent",
    "Either write something worth reading or do something worth writing",
    "There are people who have money and people who are rich",
    "You only live once, but if you do it right, once is enough",
    "Happiness lies in good health and a bad memory",
    "Your time is limited, so don’t waste it living someone else’s life",
    "Life is 10% what happens to me and 90% of how I react to it",
    "Nothing is impossible, the word itself says, I’m possible!",
    "Don't cry because it's over, smile because it happened",
    "Love is an irresistible desire to be irresistibly desired",
    "The very essence of romance is uncertainty",
    "It was love at first sight, at last sight, at ever and ever sight",
    "When love is not madness it is not love",
    "Love all, trust a few, do wrong to none",
    "The limits of my language are the limits of my world",
    "Learning is a treasure that will follow its owner everywhere",
    "Knowledge is power",
    "Learning is a gift. Even when pain is your teacher",
    "You can never be overdressed or overeducated",
    "Have no fear of perfection; you'll never reach it",
    "If a book about failures doesn't sell, is it a success?",
    "Accept who you are. Unless you're a serial killer",
    "Always forgive your enemies. Nothing annoys them more",
    "If you would like to know the value of money, try to borrow some",
    "Life would be tragic if it weren't funny",
    "The best dreams happen when you’re awake",
    "You can never be overdressed or overeducated",
    "Fall seven times and stand up eight",
    "We do not remember days, we remember moments",
    "May the Force be with you",
    "Love all, trust a few, do wrong to none",
    "I’ll think about it tomorrow",
    "Remember who you are",
    "Life is a series of choices",
    "Lost time is never found again",
    "Love is a friendship set to music",
    "Money often costs too much",
    "In the middle of difficulty lies opportunity",
    "Now or never!",
    "Everyone has one’s own path",
    "Life is beautiful. Enjoy the ride",
    "Life is a journey",
    "Enjoy every moment",
    "Feel the rain on your skin",
    "Be loyal to the one who is loyal to you",
    "Never look back",
    "Follow your heart",
    "То be or not to be",
    "Let your fears go",
    "The more you say, the less people remember",
    "Our life is what our thoughts make it",
    "Your time is limited, so don’t waste it living someone else’s life",
    "You only live once, but if you do it right, once is enough",
    "Things change. And friends leave. Life doesn’t stop for anybody",
    "Think like a man of action and act like a man of thought",
    "Every little thing is gonna be alright!",
    "You are Beautiful, no matter what they say",
    "It’s a beautiful day. Don’t let it get away",
    "When I discover who I am, I’ll be free",
    "Beware, for I am fearless, and therefore powerful",
    "To a great mind nothing is little",
]